version: 2
updates:
  # First update serves as template with common configuration
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
    cooldown:
      default-days: 5
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
    groups:
      # Specify a name for the group, which will be used in pull request titles
      # and branch names
      patches:
        applies-to: version-updates
        update-types:
          - "patch"
      docusaurus:
        applies-to: version-updates
        patterns:
          - "@docusaurus/*"

  - package-ecosystem: "npm"
    directory: "/docs-site"
    schedule:
      interval: "daily"
      time: "03:00"
    cooldown:
      default-days: 5
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
    groups:
      # Specify a name for the group, which will be used in pull request titles
      # and branch names
      patches:
        applies-to: version-updates
        update-types:
          - "patch"
    ignore:
      - dependency-name: "@docusaurus/*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
    cooldown:
      default-days: 5
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
